# Generated by Django 5.2.4 on 2026-01-08 19:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("club", "Club Marista"),
                            ("otro_club", "Otro club"),
                            ("otro", "Otro lugar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Rama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=10)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_club.division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("divisiones", models.ManyToManyField(to="app_club.division")),
                ("ramas", models.ManyToManyField(to="app_club.rama")),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("divisiones", models.ManyToManyField(to="app_club.division")),
                ("ramas", models.ManyToManyField(to="app_club.rama")),
            ],
        ),
        migrations.CreateModel(
            name="Jugadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("nro_socio", models.CharField(max_length=20)),
                ("anio_nacimiento", models.IntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_club.division",
                    ),
                ),
                (
                    "rama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_club.rama",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("divisiones", models.ManyToManyField(to="app_club.division")),
                ("ramas", models.ManyToManyField(to="app_club.rama")),
            ],
        ),
        migrations.CreateModel(
            name="Ayudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("divisiones", models.ManyToManyField(to="app_club.division")),
                ("ramas", models.ManyToManyField(to="app_club.rama")),
            ],
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Entrenamiento", "Entrenamiento"),
                            ("Partido", "Partido"),
                            ("Otra", "Otra actividad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("creado_el", models.DateTimeField(default=django.utils.timezone.now)),
                ("modificado_el", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ayudantes",
                    models.ManyToManyField(blank=True, to="app_club.ayudante"),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_club.division",
                    ),
                ),
                (
                    "entrenadores",
                    models.ManyToManyField(blank=True, to="app_club.entrenador"),
                ),
                ("managers", models.ManyToManyField(blank=True, to="app_club.manager")),
                ("pfs", models.ManyToManyField(blank=True, to="app_club.pf")),
                (
                    "rama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_club.rama"
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades",
                        to="app_club.sede",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_club.division",
                    ),
                ),
                (
                    "rama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_club.rama"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presencialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presente", models.BooleanField(default=False)),
                (
                    "rendimiento",
                    models.IntegerField(
                        blank=True,
                        help_text="Rendimiento del 1 al 10",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("creado_el", models.DateTimeField(auto_now_add=True)),
                ("modificado_el", models.DateTimeField(auto_now=True)),
                ("eliminado_el", models.DateTimeField(blank=True, null=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_club.actividad",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presenc_creada",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eliminado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presenc_eliminada",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jugadora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_club.jugadora",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presenc_modificada",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presencialidad",
                "verbose_name_plural": "Presencialidades",
                "unique_together": {("actividad", "jugadora")},
            },
        ),
        migrations.CreateModel(
            name="PresencialidadEntrenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presente", models.BooleanField(default=False)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencias_entrenadores",
                        to="app_club.actividad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencias_en_actividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("actividad", "usuario")},
            },
        ),
    ]
