# Generated by Django 5.2.4 on 2026-02-12 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_club", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrenador",
            name="nombre",
        ),
        migrations.AddField(
            model_name="entrenador",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Entrenamiento", "Entrenamiento"),
                    ("Partido", "Partido"),
                    ("Otra", "Otra"),
                ],
                max_length=20,
            ),
        ),
    ]
