# Generated by Django 5.2.4 on 2026-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_club", "0003_remove_ayudante_nombre_remove_manager_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ayudante",
            name="nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="entrenador",
            name="nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="manager",
            name="nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="pf",
            name="nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Técnico", "Técnico"),
                    ("Físico", "Físico"),
                    ("Partido", "Partido"),
                    ("Otra", "Otra"),
                ],
                max_length=20,
            ),
        ),
    ]
