# Generated by Django 5.2.4 on 2026-02-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_club", "0004_ayudante_nombre_entrenador_nombre_manager_nombre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jugadora",
            name="nro_socio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
