# Generated by Django 5.2.4 on 2026-02-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_club", "0005_alter_jugadora_nro_socio"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpermission",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Técnico", "Técnico"),
                    ("Físico", "Físico"),
                    ("Partido", "Partido"),
                    ("Otra", "Otra"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
