# Generated by Django 5.2.4 on 2026-02-16 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_club", "0006_staffpermission_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sede",
            old_name="latitud",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="sede",
            old_name="longitud",
            new_name="long",
        ),
        migrations.AddField(
            model_name="presencialidadentrenador",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presencialidadentrenador",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presencialidadentrenador",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="presencialidadentrenador",
            name="lon",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
